name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    services:
      threads:
        image: textile/go-threads:latest
        env:
          THRDS_APIPROXYADDR: /ip4/0.0.0.0/tcp/6007
        ports:
          - "127.0.0.1:6007:6007"

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache Build
      id: npm-dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: NPM Install
      run: npm install

    - name: Test Node
      run: |
           npm run test:node

    - name: Test Browser
      run: |
           npm run test:browser
